### PR TITLE
Show color options in list

### PR DESCRIPTION
**Pull request by ardjuh**
Hi, I made a list with color options which the user can choose from.

### CODE REVIEW

**Comment by avanishsubbiah** [comment]
The list is working; however, the theme doesn't seem to update when changing it to vibrant or default.

**Comment by avanishsubbiah** [comment]
image

The hook `changed::vibrant` needs to be updated to `changed::scheme` so that the extension can detect when the user has changed their color mode preference and update the theme accordingly. Once that change is made I can go forward with merging this branch into main.

**Comment by ardjuh** [comment]
I updated the hook, it already worked for me though.

**Comment by avanishsubbiah** [comment]
Thanks, the changes have been merged. For me when I was changing the extension options it wasn't updating, the hook update fixed that.

**Pull request merged**
